#!/usr/bin/env python3

from depthai_publisher import aruco_subscriber
import argparse
import rospy

def arg_parser(raw_args=None):
    # construct the argument parse and parse the arguments.
    ap = argparse.ArgumentParser()
    ap.add_argument("-ct", "--cam_topic", default="/",
                    help="camera topic name")

    if raw_args is None:
        args = vars(ap.parse_args(rospy.myargv()[1:]))
    else:
        args = vars(ap.parse_args(raw_args))

    return args

if __name__ == '__main__':
    try:
        args = arg_parser()
        aruco_subscriber.main(args)
    except Exception as e:
        print(e)
    
